# Copyright 2019 John Hurst
# John Hurst (john.b.hurst@gmail.com)
# 2019-06-14

---
- hosts: default
  tasks:
    - name: Run Crystal
      raw: bash /vagrant/crystal/run.sh Queens 8 12 >/vagrant/out-crystal.csv
