# Copyright 2019 John Hurst
# John Hurst (john.b.hurst@gmail.com)
# 2019-06-15

---
- hosts: default
  tasks:
    - name: Run Haskell
      raw: bash /vagrant/haskell/run.sh Queens 8 12 >/vagrant/out-haskell.csv

