# Copyright 2019 John Hurst
# John Hurst (john.b.hurst@gmail.com)
# 2019-06-14

---
- hosts: default
  tasks:
    - name: Install OpenJDK 8
      apt:
        name: openjdk-8-jdk
        state: present
        force_apt_get: yes
      become: yes
    - name: Run Java Queens
      raw: bash /vagrant/java/run.sh Queens 8 12 >/vagrant/out-java.csv
