# Copyright 2019 John Hurst
# John Hurst (john.b.hurst@gmail.com)
# 2019-06-15

---
- hosts: default
  tasks:
    - name: Run Julia
      raw: PATH=/usr/bin:/opt/julia-1.1.1/bin /bin/bash /vagrant/julia/run.sh Queens 8 12 >/vagrant/out-julia.csv
      # TODO: PATH setting in provisioning script should work, but does not.
