# Copyright 2019 John Hurst
# John Hurst (john.b.hurst@gmail.com)
# 2019-06-15

---
- hosts: default
  vars_files:
    - vars.yml
  environment:
    PATH: "{{ansible_env.PATH }}:{{ kotlin.root }}/bin"
  tasks:
    - name: Run Kotlin
      shell: /vagrant/kotlin/run.sh Queens 8 12 >/vagrant/out-kotlin.csv
      args:
        executable: /bin/bash
