# Copyright 2019 John Hurst
# John Hurst (john.b.hurst@gmail.com)
# 2019-06-14

---
- hosts: default
  become: yes
  tasks:

    - name: Install aptitude
      apt:
        name: aptitude
        state: present
        force_apt_get: yes
        update_cache: yes

    - name: Install language/locale support
      apt:
        name: language-pack-en
        state: present

    - name: Install unzip
      apt:
        name: unzip
        state: present

    - name: Install openjdk-8-jdk
      apt:
        name: openjdk-8-jdk
        state: present

    - name: Install Clojure
      apt:
        name: clojure
        state: present

    - name: Add key for Crystal language
      apt_key:
        url: https://keybase.io/crystal/pgp_keys.asc
        state: present

    - name: Define repo for Crystal language
      apt_repository:
        repo: deb https://dist.crystal-lang.org/apt crystal main
        state: present

    - name: Install Crystal language
      apt:
        name: crystal
        state: present

    - name: Add key for Microsoft
      apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc
        state: present

    - name: Define repo for Microsoft .NET Core
      apt_repository:
        repo: deb https://packages.microsoft.com/ubuntu/18.04/prod bionic main
        state: present

    - name: Install .NET Core
      apt:
        name: dotnet-sdk-2.2
        state: present
        update_cache: yes

    - name: Install Elixir repo
      apt:
        deb: https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb
        state: present

    - name: Install Erlang/OTP platform and all of its applications
      apt:
        name: esl-erlang
        state: present
        update_cache: yes

    - name: Install Elixir
      apt:
        name: elixir
        state: present
        update_cache: yes

    - name: Install Go
      apt:
        name: golang-go
        state: present

    - name: Install Groovy
      apt:
        name: groovy
        state: present

    - name: Install Haskell
      apt:
        name: haskell-platform
        state: present

    - name: Install nodejs
      apt:
        name: nodejs
        state: present

    - name: Download Julia archive
      get_url:
        url: https://julialang-s3.julialang.org/bin/linux/x64/1.1/julia-1.1.1-linux-x86_64.tar.gz
        dest: /tmp/julia-1.1.1-linux-x86_64.tar.gz

    - name: Unpack Julia archive
      unarchive:
        remote_src: yes
        src: /tmp/julia-1.1.1-linux-x86_64.tar.gz
        dest: /opt/
        creates: /opt/julia-1.1.1

    # This doesn't seem to work!!! Instead, see symlink below.
    - name: Set PATH for Julia
      copy:
        dest: /etc/profile.d/julia-path.sh
        content: 'PATH=$PATH:/opt/julia-1.1.1/bin'

    - name: Create symlink for Julia
      file:
        src: /opt/julia-1.1.1/bin/julia
        dest: /usr/bin/julia
        owner: root
        group: root
        state: link

    - name: Download Kotlin archive
      get_url:
        url: https://github.com/JetBrains/kotlin/releases/download/v1.3.31/kotlin-compiler-1.3.31.zip
        dest: /tmp/kotlin-compiler-1.3.31.zip

    - name: Unpack Kotlin archive
      unarchive:
        remote_src: yes
        src: /tmp/kotlin-compiler-1.3.31.zip
        dest: /opt/
        creates: /opt/kotlinc

    # This doesn't seem to work!!! Instead, see symlink below.
    - name: Set PATH for Kotlin
      copy:
        dest: /etc/profile.d/kotlin-path.sh
        content: 'PATH=$PATH:/opt/kotlinc/bin'

    - name: Create symlink for Kotlin
      file:
        src: /opt/kotlinc/bin/kotlinc
        dest: /usr/bin/kotlinc
        owner: root
        group: root
        state: link

    - name: Install Ruby
      apt:
        name: ruby
        state: present

    - name: Install Scala
      apt:
        name: scala
        state: present

    - name: Install clang dependency for Swift
      apt:
        name: clang
        state: present

    - name: Install libicu-dev dependency for Swift
      apt:
        name: libicu-dev
        state: present

    - name: Download Swift archive
      get_url:
        url: https://swift.org/builds/swift-5.0.1-release/ubuntu1804/swift-5.0.1-RELEASE/swift-5.0.1-RELEASE-ubuntu18.04.tar.gz
        dest: /tmp/swift-5.0.1-RELEASE-ubuntu18.04.tar.gz

    - name: Unpack Swift archive
      unarchive:
        remote_src: yes
        src: /tmp/swift-5.0.1-RELEASE-ubuntu18.04.tar.gz
        dest: /opt/
        creates: /opt/swift-5.0.1-RELEASE-ubuntu18.04

    # This doesn't seem to work!!! Instead, see symlink below.
    - name: Set PATH for Swift
      copy:
        dest: /etc/profile.d/swift-path.sh
        content: 'PATH=$PATH:/opt/swift-5.0.1-RELEASE-ubuntu18.04/usr/bin'

    - name: Create symlink for Swift
      file:
        src: /opt/swift-5.0.1-RELEASE-ubuntu18.04/usr/bin/swiftc
        dest: /usr/bin/swiftc
        owner: root
        group: root
        state: link
