# Copyright 2019 John Hurst
# John Hurst (john.b.hurst@gmail.com)
# 2019-06-14

---
- hosts: default
  tasks:
    - name: Run Python3
      raw: bash /vagrant/python/run.sh Queens 8 12 >/vagrant/out-python.csv

