# Copyright 2019 John Hurst
# John Hurst (john.b.hurst@gmail.com)
# 2019-06-15

---
- hosts: default
  tasks:
    - name: Run Ruby
      raw: bash /vagrant/ruby/run.sh Queens 8 12 >/vagrant/out-ruby.csv
