# Copyright 2019 John Hurst
# John Hurst (john.b.hurst@gmail.com)
# 2019-06-15

---
- hosts: default
  tasks:
    - name: Run Scala
      raw: bash /vagrant/scala/run.sh Queens 8 12 >/vagrant/out-scala.csv
