# Copyright 2019 John Hurst
# John Hurst (john.b.hurst@gmail.com)
# 2019-06-15

---
- hosts: default
  vars_files:
    - vars.yml
  environment:
    PATH: "{{ansible_env.PATH }}:{{ swift.root }}/usr/bin"
  tasks:
    - name: Run Swift
      shell: /vagrant/swift/run.sh Queens 8 12 >/vagrant/out-swift.csv
      args:
        executable: /bin/bash
