# Copyright 2019 John Hurst
# John Hurst (john.b.hurst@gmail.com)
# 2019-06-16

julia:
  root: /opt/julia-1.1.1
  base_url: https://julialang-s3.julialang.org/bin/linux/x64/1.1
  archive: julia-1.1.1-linux-x86_64.tar.gz

kotlin:
  root: /opt/kotlinc
  base_url: https://github.com/JetBrains/kotlin/releases/download/v1.3.31
  archive: kotlin-compiler-1.3.31.zip

swift:
  root: /opt/swift-5.0.1-RELEASE-ubuntu18.04
  base_url: https://swift.org/builds/swift-5.0.1-release/ubuntu1804/swift-5.0.1-RELEASE
  archive: swift-5.0.1-RELEASE-ubuntu18.04.tar.gz
